package com.alterdata.calculo.irpf.contants;


public enum AliquotaINSS {

    FAIXA_SALARIAL1_ALIQUOTA (7.5),
    FAIXA_SALARIAL1_VALOR_INICIAL (1045.00),
    FAIXA_SALARIAL1_PARCELA_DEDUTIVEL(0),

    FAIXA_SALARIAL2_ALIQUOTA (9),
    FAIXA_SALARIAL2_VALOR_INICIAL (1045.01),
    FAIXA_SALARIAL2_VALOR_FINAL (2089.60),
    FAIXA_SALARIAL2_PARCELA_DEDUTIVEL(15.67),

    FAIXA_SALARIAL3_ALIQUOTA (12),
    FAIXA_SALARIAL3_VALOR_INICIAL (2089.61),
    FAIXA_SALARIAL3_VALOR_FINAL (3131.40),
    FAIXA_SALARIAL3_PARCELA_DEDUTIVEL(78.36),

    FAIXA_SALARIAL4_ALIQUOTA (14),
    FAIXA_SALARIAL4_VALOR_INICIAL (31134.41),
    FAIXA_SALARIAL4_VALOR_FINAL (6101.06),
    FAIXA_SALARIAL4_PARCELA_DEDUTIVEL(141.05);

    private final double value;

    AliquotaINSS(double faixa) {
        this.value = faixa;
    }

    public static double value(int key){
        return AliquotaINSS.values()[key - 1].value;
    }


}
