package com.alterdata.calculo.irpf.services.calculo_mensal.constants;


public enum AliquotaMensalINSS {

    FAIXA_SALARIAL1_ALIQUOTA (7.5),
    FAIXA_SALARIAL1_VALOR_FINAL (1045.00),
    FAIXA_SALARIAL1_PARCELA_DEDUTIVEL(0),

    FAIXA_SALARIAL2_ALIQUOTA (9),
    FAIXA_SALARIAL2_VALOR_INICIAL (1045.01),
    FAIXA_SALARIAL2_VALOR_FINAL (2089.60),
    FAIXA_SALARIAL2_PARCELA_DEDUTIVEL(15.67),

    FAIXA_SALARIAL3_ALIQUOTA (12),
    FAIXA_SALARIAL3_VALOR_INICIAL (2089.61),
    FAIXA_SALARIAL3_VALOR_FINAL (3134.40),
    FAIXA_SALARIAL3_PARCELA_DEDUTIVEL(78.36),

    FAIXA_SALARIAL4_ALIQUOTA (14),
    FAIXA_SALARIAL4_VALOR_INICIAL (3134.41),
    FAIXA_SALARIAL4_VALOR_FINAL (6101.06),
    FAIXA_SALARIAL4_PARCELA_DEDUTIVEL(141.05),

    TETO_INSS(713.10);

    private final double value;

    AliquotaMensalINSS(double faixa) {
        this.value = faixa;
    }

    public double value(){
        return value;
    }


}
