package com.alterdata.calculo.irpf.services.calculo_mensal.constants;


public enum AliquotaMensalINSS {
    FAIXA_SALARIAL1_ALIQUOTA(7.5),
    FAIXA_SALARIAL1_VALOR_FINAL(1100.00),
    FAIXA_SALARIAL1_PARCELA_DEDUTIVEL(0),

    FAIXA_SALARIAL2_ALIQUOTA(9),
    FAIXA_SALARIAL2_VALOR_INICIAL(1100.01),
    FAIXA_SALARIAL2_VALOR_FINAL(2203.48),
    FAIXA_SALARIAL2_PARCELA_DEDUTIVEL(16.50),

    FAIXA_SALARIAL3_ALIQUOTA(12),
    FAIXA_SALARIAL3_VALOR_INICIAL(2203.49),
    FAIXA_SALARIAL3_VALOR_FINAL(3305.22),
    FAIXA_SALARIAL3_PARCELA_DEDUTIVEL(82.604),

    FAIXA_SALARIAL4_ALIQUOTA(14),
    FAIXA_SALARIAL4_VALOR_INICIAL(3305.23),
    FAIXA_SALARIAL4_VALOR_FINAL(6433.57),
    FAIXA_SALARIAL4_PARCELA_DEDUTIVEL(148.708),

    TETO_INSS(751.97);

    private final double value;

    AliquotaMensalINSS(double faixa) {
        this.value = faixa;
    }

    public double value() {
        return value;
    }


}
